version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rubocop
    versions:
    - 1.12.0
    - 1.12.1
  - dependency-name: listen
    versions:
    - 3.5.0
  - dependency-name: rubocop-performance
    versions:
    - 1.10.2
  - dependency-name: bootsnap
    versions:
    - 1.7.3
  - dependency-name: rspec-rails
    versions:
    - 4.1.0
